# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
 
Vagrant.configure(2) do |config|
 
  config.vm.box = "andriy-koval/win-server-2012r2"
  config.vm.box_version = "1.1.2"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", host: 3389, guest: 3389, id: "rdp", auto_correct: true
  config.winrm.username = "Administrator"
  config.winrm.password = "P@$$w0rd!"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
     
    # Customize the amount of memory on the VM:
    vb.cpus = 2
    vb.memory = 2048
  end
  
  config.vm.define "winserver" do |winserver|
    winserver.vm.host_name = "winserver"
  end

end
