# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.network "public_network"
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.provision "docker"
  config.vm.provision "shell", inline: <<-SHELL
    sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
  SHELL

config.vm.provider "virtualbox" do |v|
  v.memory = "1024"
  v.cpus = 2
end

  config.vm.define "docker" do |docker|
    docker.vm.hostname = "docker"
#   docker.vm.network "private_network", ip: "192.168.10.10"
  end
end
