# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.network "public_network"
  config.vm.box = "ubuntu/xenial64"

config.vm.provider "virtualbox" do |v|
  v.memory = "1024"
  v.cpus = 2
end

  config.vm.define "server1" do |server1|
    server1.vm.hostname = "server1"
#   server1.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "server2" do |server2|
    server2.vm.hostname = "server2"
#   server2.vm.network "private_network", ip: "192.168.10.11"
  end

  config.vm.define "server3" do |server3|
    server3.vm.hostname = "server3"
#   server3.vm.network "private_network", ip: "192.168.10.12"
  end
end
